### ISSUE TITLE
Wadaw

### ISSUE THREAD

**Issue by arisawali2014** [xxxtentakel/WadawGojek#1]
Cuman sebentar ya, langsung koid.

**Comment by xxxtentakel** [comment]
> Cuman sebentar ya, langsung koid.

Walahhh langsung koid ya? Gercep amat wkwk

**Comment by arisawali2014** [comment]
> {"data":null,"success":false,"errors":[{"code":"GoPromo-InvalidPromoCode","message":"Seems like this promo code is fully redeemed or invalid.","message_title":"Hmm, couldn't find this code","message_severity":"error"}]}

Akwoakwoak

**Comment by arisawali2014** [comment]
Bisa jadi kalo emang kuotanya udh abis. Kalo misalkan device id ga mungkin, kan bikin random

**Comment by arisawali2014** [comment]
confirmed. setelah coba bikin jam 12 malem. udah abis. fix Koid.
